version: '2'
services:
  selenium_hub:
    image: r.cfcr.io/dustinvanbuskirk/example-voting-app/vote:testing-c4cc03e
    ports:
      - 4444
    environment:
      - SE_OPTS=-debug
      - GRID_MAX_SESSION=5
  chrome_node:
    image: selenium/node-chrome:3.13.0
    ports:
      - 5900
      - 5555
    command: bash -c "sleep 5 && /opt/bin/entry_point.sh"
    depends_on: 
      - selenium_hub
    environment:
      - HUB_HOST=selenium_hub
      - REMOTE_HOST=http://chrome_node:5555
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
  firefox_node:
    image: selenium/node-firefox:3.13.0
    ports:
      - 5900
      - 5555
    command: bash -c "sleep 5 && /opt/bin/entry_point.sh"
    depends_on: 
      - selenium_hub
    environment:
      - HUB_HOST=selenium_hub
      - REMOTE_HOST=http://firefox_node:5555
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5