apiVersion: v1
kind: Secret
metadata:
  name: "postgresql-{{ .Release.Name }}"
  labels:
    app: example-voting-app
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  password: {{ .Values.postgresql.postgresPassword }}